####################################################################################################
## YAML file for github Actions that will perform project checking for adhering to doxygen        ##
## documentation standards and to also deploy the generated HTML documentation to gh-pages        ##
##                                                                                                ##
## Version Date       Developer      Comments                                                     ##
## ======= ========== ============== ============================================================ ##
## 1.0.1   2021-01-27 SV-Zanshin     Fixed project type                                           ##
## 1.0.0   2021-01-21 SV-Zanshin     Cloned from default and updated                              ##
##                                                                                                ##
####################################################################################################
name: 'Doxygen'

####################################################################################################
## Action runs when committing (push), doing a pull request, or a workflow_dispatch               ##
####################################################################################################
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  doxygen:
    name: 'Generate doxygen'
    runs-on: ubuntu-latest
    steps:
       - name: 'Checkout the repository from github'
         uses: actions/checkout@v2
       - name: 'Checkout the "Zanduino/Common" repository from github'
         uses: actions/checkout@v2
         with:
           repository: Zanduino/Common
           path: Common
       - name: 'Create doxygen html documentation'
         env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          ##########################################################################################
          ## The following 5 lines need to be set here each project                               ##
          ##########################################################################################
          PRETTYNAME:     "Zanduino SmoothLED Library 8-bit"
          PROJECT_NAME:   "SmoothLED"
          PROJECT_NUMBER: "v1.0.0"
          PROJECT_BRIEF:  "Zanduino Arduino Library for controlling 8-bit PWM on any pin"
          PROJECT_LOGO:   ""
         run: bash ${GITHUB_WORKSPACE}/Common/Scripts/doxy_gen_and_deploy.sh
